//go:build metricnames

package main

import (
	"errors"
	"flag"
	"fmt"
	"os"

	"github.com/arloliu/mebo/blob"
	"github.com/arloliu/mebo/endian"
	meboerrs "github.com/arloliu/mebo/errs"
	ienc "github.com/arloliu/mebo/internal/encoding"
	"github.com/arloliu/mebo/section"
)

// mnNameA, mnNameB, and mnCollisionID mirror internal/collisiontest's
// NameA/NameB/CollisionID (a real, verified xxHash64 collision pair found via
// Floyd cycle detection and committed as a self-verifying fixture)
// verbatim. They are duplicated here — rather than importing
// internal/collisiontest directly — because `go mod tidy` resolves every
// import reachable from any source file in the module regardless of active
// build tags (it computes the package graph for all build configurations,
// not just the one currently being compiled). internal/collisiontest is a
// v1.10.0+-only package; importing it from this metricnames-tag-gated file
// would still make `go mod tidy` fail when building the compat binary
// against a pre-v1.10.0 module (e.g. v1.9.0), which lacks that package
// entirely, even though this file is never compiled into that binary.
// internal/encoding (ienc, below) predates v1.10.0 and does not have this
// problem — only the package needs to resolve for `go mod tidy`, not the
// specific symbols used, and those are only referenced from code gated the
// same way.
//
// blob/metric_names_collision_test.go's TestCollisionPair (via
// internal/collisiontest) is the self-verifying guard that these stay
// correct if the hash function or fixture strings ever change.
const (
	mnNameA              = "mebo.collision.probe.9311205776335484502"
	mnNameB              = "mebo.collision.probe.12220231876399211248"
	mnCollisionID uint64 = 0x81cd12cc642d886c
)

// This file builds the two adversarial "must reject" fixtures for the
// v1.10.0 metric-names decode hardening: a duplicate metric name in one blob,
// and an unsorted-by-ID V2 index. Both bytes-level
// constructions are impossible to reach through the public encoder API by
// design — the encoder actively rejects re-adding a name after a collision
// (ErrMetricAlreadyStarted) and always sorts V2 index entries by MetricID —
// so they are built once here, deterministically, by first encoding
// a structurally valid blob through the public API and then patching it at
// the byte level using only public packages (blob, section, endian) plus the
// module-internal (but import-path-shared, see the mnNameA/B doc comment
// above) internal/encoding package that already backs the equivalent
// in-module regression tests (blob/metric_names_collision_test.go,
// blob/metric_names_boundary_test.go). Nothing here is reachable from
// application code — it exists solely to produce hostile bytes for the
// decoder's rejection path, which is then exercised through ONLY the public
// blob.NewNumericDecoder / Decode API (see main.go's decode/reject flow).
//
// Because construction is fully deterministic (fixed collision pair, fixed
// base time, fixed names/IDs), re-running `compat mncorrupt` always
// reproduces the exact checked-in fixture bytes deterministically, without
// hand-maintaining committed binary blobs (tests/compat/testdata
// is gitignored and regenerated by every compat run, same as the existing
// `compat corrupt` corruption fixtures).

func init() {
	mnCorruptImpl = runMnCorruptImpl

	// Register the sentinels the two fixtures below must be rejected with,
	// keyed by the same string main.go's runDecode looks up via a
	// Manifest.ExpectErrIs value (see writeMnFixture). This is the only
	// place these two errs symbols are referenced in the whole compat
	// module — both are new to v1.10.0+ (see errs/errors.go) and don't
	// exist in v1.9.0's errs package, so referencing them from an
	// unconditionally-compiled file such as main.go would break the
	// v1.9.0 build. This file only compiles under the "metricnames" build
	// tag, i.e. only when the module being built against already has them.
	namedSentinels["ErrDuplicateMetricName"] = meboerrs.ErrDuplicateMetricName
	namedSentinels["ErrUnsortedIndex"] = meboerrs.ErrUnsortedIndex
}

func runMnCorruptImpl(args []string) error {
	fs := flag.NewFlagSet("mncorrupt", flag.ExitOnError)
	outdir := fs.String("outdir", "", "output directory for metric-names adversarial fixtures (required)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *outdir == "" {
		return errors.New("--outdir is required")
	}
	if err := os.MkdirAll(*outdir, 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", *outdir, err)
	}

	dup, err := buildDuplicateNameFixture()
	if err != nil {
		return fmt.Errorf("build mn-dup-name fixture: %w", err)
	}
	if err := writeMnFixture(*outdir, "mn-dup-name", dup, "ErrDuplicateMetricName"); err != nil {
		return err
	}
	fmt.Printf("  mncorrupt mn-dup-name %35s OK (%d bytes)\n", "", len(dup))

	unsorted, err := buildUnsortedV2Fixture()
	if err != nil {
		return fmt.Errorf("build mn-unsorted-v2 fixture: %w", err)
	}
	if err := writeMnFixture(*outdir, "mn-unsorted-v2", unsorted, "ErrUnsortedIndex"); err != nil {
		return err
	}
	fmt.Printf("  mncorrupt mn-unsorted-v2 %31s OK (%d bytes)\n", "", len(unsorted))

	fmt.Printf("\nGenerated 2 metric-names adversarial fixture(s) in %s\n", *outdir)

	return nil
}

// writeMnFixture writes the fixture's blob bytes plus its manifest.
//
// Metrics is deliberately nil: both fixtures are hostile, byte-patched
// constructions (see buildDuplicateNameFixture / buildUnsortedV2Fixture)
// built specifically so the decoder MUST reject them — there is no
// well-defined "correct" decoded metric set to assert field-by-field even
// when they're rejected as designed. This is safe because, unlike the
// pre-this-branch reject path, whether the row passes no longer depends in
// any way on Metrics or the resulting VerifyResult.OK(): runDecode's
// expectError branch (main.go) checks only the decode step's own error
// (VerifyResult.DecodeErr / a recovered panic) via errors.Is against
// expectErrIs, so a nil Metrics slice cannot be the mechanism by which this
// row passes — a decoder that wrongly accepts either fixture still fails the
// row (DecodeErr stays nil, which runDecode's "decoding succeeded" branch
// FAILs on) regardless of what Metrics says.
func writeMnFixture(outdir, id string, data []byte, expectErrIs string) error {
	if err := writeBlobFile(outdir, id, data); err != nil {
		return err
	}
	m := &Manifest{
		ScenarioID:  id,
		BlobType:    BlobTypeNumeric,
		Format:      FormatV2,
		Metrics:     nil,
		ExpectErrIs: expectErrIs,
	}

	return writeManifest(outdir, m)
}

// buildDuplicateNameFixture builds a V2 numeric blob whose names payload is
// [NameA, NameB, NameA] (an A/B/A repeated-name shape: the same name
// reappears non-adjacently, with a distinct name in between) and whose three
// index entries all declare MetricID == CollisionID. Because NameA and NameB
// both genuinely hash to CollisionID (internal/collisiontest), the
// decoder's per-name hash verification (VerifyMetricNamesHashes) passes for
// all three entries, isolating the failure to the duplicate-name check
// (ErrDuplicateMetricName) — not an earlier hash-mismatch error.
func buildDuplicateNameFixture() ([]byte, error) {
	start := baseStartTime
	enc, err := blob.NewNumericEncoder(start, blob.WithBlobLayoutV2(), blob.WithMetricNames(), blob.WithLittleEndian())
	if err != nil {
		return nil, fmt.Errorf("new encoder: %w", err)
	}

	placeholders := []string{"mn.dupfixture.a", "mn.dupfixture.b", "mn.dupfixture.c"}
	for i, nm := range placeholders {
		if err := enc.StartMetricName(nm, 1); err != nil {
			return nil, fmt.Errorf("start %s: %w", nm, err)
		}
		if err := enc.AddDataPoint(baseTimestampUs+int64(i)*1_000_000, float64(i), ""); err != nil {
			return nil, fmt.Errorf("add point %s: %w", nm, err)
		}
		if err := enc.EndMetric(); err != nil {
			return nil, fmt.Errorf("end %s: %w", nm, err)
		}
	}

	data, err := enc.Finish()
	if err != nil {
		return nil, fmt.Errorf("finish: %w", err)
	}

	engine := endian.GetLittleEndianEngine()

	hdr, err := section.ParseNumericHeader(data)
	if err != nil {
		return nil, fmt.Errorf("parse header: %w", err)
	}

	oldNames, oldLen, err := ienc.DecodeMetricNames(data[section.HeaderSize:], engine)
	if err != nil {
		return nil, fmt.Errorf("decode names: %w", err)
	}
	if len(oldNames) != len(placeholders) {
		return nil, fmt.Errorf("expected %d names, got %d", len(placeholders), len(oldNames))
	}

	// Splice in [NameA, NameB, NameA], shifting every downstream absolute
	// offset by the resulting size delta — mirrors the technique in
	// blob/metric_names_collision_test.go's TestDecoder_DuplicateName.
	newNames, err := ienc.EncodeMetricNames([]string{mnNameA, mnNameB, mnNameA}, engine)
	if err != nil {
		return nil, fmt.Errorf("encode replacement names: %w", err)
	}

	// These offsets are always well within uint32 range for the small,
	// fixed-size fixtures this file builds (mirrors the identical pattern in
	// blob/metric_names_collision_test.go's TestDecoder_DuplicateName).
	delta := len(newNames) - oldLen
	hdr.IndexOffset = uint32(int(hdr.IndexOffset) + delta)                       //nolint:gosec // fixed-size fixture: offset+delta always fits uint32.
	hdr.TimestampPayloadOffset = uint32(int(hdr.TimestampPayloadOffset) + delta) //nolint:gosec // fixed-size fixture: offset+delta always fits uint32.
	hdr.ValuePayloadOffset = uint32(int(hdr.ValuePayloadOffset) + delta)         //nolint:gosec // fixed-size fixture: offset+delta always fits uint32.
	hdr.TagPayloadOffset = uint32(int(hdr.TagPayloadOffset) + delta)             //nolint:gosec // fixed-size fixture: offset+delta always fits uint32.

	out := make([]byte, 0, len(data)+delta)
	out = append(out, hdr.Bytes()...)
	out = append(out, newNames...)
	out = append(out, data[section.HeaderSize+oldLen:]...)

	// Force every index entry's declared MetricID to CollisionID so it
	// matches hash.ID(NameA) == hash.ID(NameB) for all three positions.
	hdr2, err := section.ParseNumericHeader(out)
	if err != nil {
		return nil, fmt.Errorf("re-parse header after splice: %w", err)
	}
	entrySize := section.NumericIndexEntrySize
	for i := range placeholders {
		off := int(hdr2.IndexOffset) + i*entrySize
		if off+8 > len(out) {
			return nil, fmt.Errorf("index entry %d out of range", i)
		}
		engine.PutUint64(out[off:off+8], mnCollisionID)
	}

	return out, nil
}

// buildUnsortedV2Fixture builds a valid 2-entry V2 numeric blob (IDs [100,
// 200], no names payload) and patches the first index entry's MetricID to
// 300, producing a descending-order [300, 200] index — the shape the
// decoder must reject with ErrUnsortedIndex. Mirrors
// blob/metric_names_boundary_test.go's TestUnsortedV2_Rejected
// ("descending pair" case).
func buildUnsortedV2Fixture() ([]byte, error) {
	start := baseStartTime
	enc, err := blob.NewNumericEncoder(start, blob.WithBlobLayoutV2(), blob.WithLittleEndian())
	if err != nil {
		return nil, fmt.Errorf("new encoder: %w", err)
	}

	ids := []uint64{100, 200}
	for _, id := range ids {
		if err := enc.StartMetricID(id, 1); err != nil {
			return nil, fmt.Errorf("start id %d: %w", id, err)
		}
		if err := enc.AddDataPoint(baseTimestampUs, 1.0, ""); err != nil {
			return nil, fmt.Errorf("add point id %d: %w", id, err)
		}
		if err := enc.EndMetric(); err != nil {
			return nil, fmt.Errorf("end id %d: %w", id, err)
		}
	}

	data, err := enc.Finish()
	if err != nil {
		return nil, fmt.Errorf("finish: %w", err)
	}

	hdr, err := section.ParseNumericHeader(data)
	if err != nil {
		return nil, fmt.Errorf("parse header: %w", err)
	}

	engine := endian.GetLittleEndianEngine()
	off := int(hdr.IndexOffset) // entry 0
	if off+8 > len(data) {
		return nil, errors.New("index entry 0 out of range")
	}
	engine.PutUint64(data[off:off+8], 300) // [300, 200] — descending

	return data, nil
}
