// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package numericblob

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NumericMetricSet struct {
	_tab flatbuffers.Table
}

func GetRootAsNumericMetricSet(buf []byte, offset flatbuffers.UOffsetT) *NumericMetricSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NumericMetricSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishNumericMetricSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNumericMetricSet(buf []byte, offset flatbuffers.UOffsetT) *NumericMetricSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NumericMetricSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNumericMetricSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NumericMetricSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NumericMetricSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NumericMetricSet) Metrics(obj *NumericMetric, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *NumericMetricSet) MetricsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func NumericMetricSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}

func NumericMetricSetAddMetrics(builder *flatbuffers.Builder, metrics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(metrics), 0)
}

func NumericMetricSetStartMetricsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func NumericMetricSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
