// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package textblob

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TextBlobSet struct {
	_tab flatbuffers.Table
}

func GetRootAsTextBlobSet(buf []byte, offset flatbuffers.UOffsetT) *TextBlobSet {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TextBlobSet{}
	x.Init(buf, n+offset)
	return x
}

func FinishTextBlobSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTextBlobSet(buf []byte, offset flatbuffers.UOffsetT) *TextBlobSet {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TextBlobSet{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTextBlobSetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TextBlobSet) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TextBlobSet) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TextBlobSet) Metrics(obj *TextMetric, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TextBlobSet) MetricsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TextBlobSetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}

func TextBlobSetAddMetrics(builder *flatbuffers.Builder, metrics flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(metrics), 0)
}

func TextBlobSetStartMetricsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}

func TextBlobSetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
